### PR TITLE
Added CDN for Materialize and Bootstrap

### PR DESCRIPTION
**Pull request by Azbo400**
Hello! I added in CDN's for Materialize CSS and Boostrap and will use those now to create the navbar.

### CODE REVIEW

**Comment by xGabey** [comment]
Awesome! One thing I noticed, (typing from my phone as i leave :-)    ) is
that the border -bottom for the navbar doesn't span all the way. I've fixed
it many times on other things but I really can't figure out how to do it on
this one. That is basically step one, I guess. Just a heads up.
p.s. the vid was gr8!

**Comment by Azbo400** [comment]
Okay, I will just work on the new navbar with materialize on a separate branch then open a pull request

**Comment by xGabey** [comment]
Ok, only if you have time, then that would be great.

**Comment by Azbo400** [comment]
😄 I got time for that its pretty easy feel free to merge when ready!!

**Comment by xGabey** [comment]
Dar ye go!

**Comment by Azbo400** [comment]
👍

**Comment by xGabey** [comment]
btw, are you 'watching' this repo or no. just wondering if that would be efficient.

**Comment by xGabey** [comment]
is there one 'global' github chat, or just for each pull request? i guess that's why we'd need to use gitter.

**Comment by Azbo400** [comment]
Yeah thats what gitter is for
This is the chat to discuss the feature and see if it is good for merging or there needs to be improvements first

**Comment by xGabey** [comment]
got it, that's perfect. I really have to go now. :)

**Comment by Azbo400** [comment]
👋

**Pull request merged**
